apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: oci-native-ingress
  namespace: native-ingress-controller-system
spec:
  compartmentId: ${COMPARTMENT_ID}
  subnetId: ${SUBNET_ID}
  loadBalancerName: ${LB_NAME}
  isPrivate: false
  maxBandwidthMbps: 500
  minBandwidthMbps: 100
  # reservedPublicAddressId: <reserved-ip-ocid>
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: oci-native-ingress
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: native-ingress-controller-system
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: oci-native-ingress