---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: langfuse
  namespace: langfuse
spec:
  parentRefs:
  - name: langfuse
    sectionName: https
  hostnames:
  - ${LANGFUSE_HOSTNAME}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: langfuse-web
      port: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: langfuse-web-cert
  namespace: langfuse
spec:
  secretName: langfuse-web-ssl-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ${LANGFUSE_HOSTNAME}
